---
title: "UCSB Library Open Science Services & Support Inventory Project"
toc: false
citation: false
copyright: "Copyright © 2026 by the authors"
license: "Licensed under CC BY-NC 4.0"
---

<br/>

## Project description

Between April and December 2025, the UCSB Library conducted an internal review of our current programs, services, training, tools, and resources supporting **open science**. This project aimed to (1) develop a comprehensive inventory of existing offerings and (2) identify strategic opportunities for growth. This webpage provides a high-level overview of our findings.

<div id="diagram"></div>

<script type="module">

  const IMAGE_DISPLAY_WIDTH = 1000; // pixels
  const IMAGE_PATH = "/images/static-png";
  const UNHIGHLIGHTED_IMAGE_PATH = `${IMAGE_PATH}/00-no-highlight.png`;
  const CSV_PATH = "data_processed/label_angles.csv";

  // Assumption: commas don't appear in label names, so no need for full CSV
  // parser.

  async function load_csv() {
    const response = await fetch(CSV_PATH);
    const body = await response.text();
    const [header, ...rows] = body.trim().split("\n");
    const columns = header.split(",");
    const data = rows.map(
      row => Object.fromEntries(row.split(",").map((v, i) => [columns[i], v]))
    );
    data.forEach(item => {
      item["Viz.ID"] = parseInt(item["Viz.ID"]);
      item["Start.Degree"] = parseFloat(item["Start.Degree"]);
      item["End.Degree"] = parseFloat(item["End.Degree"]);
    });
    return data;
  }

  const data = await load_csv();
  const min_angle = Math.min(...data.map(item => item["Start.Degree"]));

  const img = document.createElement("img");
  img.src = UNHIGHLIGHTED_IMAGE_PATH;
  img.width = IMAGE_DISPLAY_WIDTH;
  img.style.cursor = "pointer";

  // Data assumptions:
  //   - Angles use the same periodic coordinate system as atan2.
  //   - Angles increase linearly from a minimum value (possibly negative) to a
  //     maximum value; there's no wrapping at +/-180.
  //   - The total range of angles is less than or equal to 360.
  //   - If items A and B are adjacent, then
  //     A["End.Degree"] == B["Start.Degree"] or vice versa.

  function switch_image(event) {
    const rect = img.getBoundingClientRect();
    const x = event.clientX - (rect.left + rect.width/2);
    const y = (rect.top + rect.height/2) - event.clientY;
    let angle = Math.atan2(y, x) * 180/Math.PI;
    if (angle < min_angle) angle += 360;
    const item = data.find(
      item => (item["Start.Degree"] <= angle && angle <= item["End.Degree"])
    );
    if (item !== undefined) {
      img.src = `${IMAGE_PATH}/${String(item["Viz.ID"]).padStart(2, "0")}.png`;
    } else {
      img.src = UNHIGHLIGHTED_IMAGE_PATH;
    }
  }

  img.addEventListener("click", switch_image);
  document.getElementById("diagram").appendChild(img);

</script>

Chord diagram showing connections between open science activities at UCSB Library

<br/>


## Findings

Our inventory captured 40+ distinct offerings, including

* [Services & Programs](services.qmd)
* [Instruction & Consultation](instruction.qmd)
* [Engagement & Community](engagement.qmd)

As part of the inventory process, **a mapping of relationships** among offerings, providers, and open science topical domains organically emerged. Rather than existing in isolation, these activities form a highly **interconnected network** of support across the library.

Interact with the visual above by hovering over individual elements. Additional details about specific activities can be explored through the other tabs on this site. 

### Key Takeaways

* Open science support at UCSB Library spans a wide range of services, instructional activities, and community engagement efforts.
* Many offerings are interconnected through shared contributors, tools, or topical focus areas.
* Viewing these activities as a network, rather than as a list, reveals opportunities for coordination, alignment, and internal awareness.

<br/>

## Project Team 

This project would not have been possible without the dedicated contribution of the following team members (listed alphabetically by last name)

* Akshay Agrawal
* Amber Budden (Project Sponsor)
* Julien Brun
* Seth Erickson
* Jon Jablonski
* Greg Janée
* Kristen LaBonte
* Xiuqi “Jade” Li (Project Manager)

<br/>

## Acknowledgement

The project team would like to thank colleagues who provided valuable feedback and suggestions during the development of this project, in particular Angela Chikowero, Renata Curty, Tina Lin, Shima Moradi, Chizu Morihara, Virginia Scarlett, and Cathy Williams. 

<br/>

## Citation and Contact

:::{.callout-tip}
## Please cit this work as

Li X, Agrawal A, Budden A, Brun J, Erickson S, Jablonski J, Janée J, LaBonte K (2026). UCSB Library Open Science Services & Support Project.
:::

For questions related to this inventory project, please email xiuqili[AT]ucsb.edu. 

_** This inventory reflects open science programs, services, and activities at UCSB Library as of December 2025._


